#!/bin/sh
set -e

install -d -m0755 idrac-kvm-keyboard-fix
cd idrac-kvm-keyboard-fix
git init
git config --get remote.origin.url >/dev/null \
|| git remote add origin https://github.com/anchor/idrac-kvm-keyboard-fix
git fetch
git pull origin master
make
echo 'IGNORE the above message, do not run make install. All done!'
